model: "stabilityai/sdxl-turbo"
variant: "fp16"
model_name: "auto"
image_size: 512
float_dtype: "float16"

scale: 0
seed: 42
ddim_steps: 4

selected_layers : [
        ['unet.mid_block.attentions.0',
        'unet.mid_block.resnets.0',
        'unet.mid_block.resnets.1']
        ]

selected_layers_style : [
        ['unet.up_blocks.0.attentions.0',
        'unet.up_blocks.0.resnets.0',
        ]
        ]